version: '3'
services:
  db:
    image: mysql:5.7
    ports:
     - "3232:3306"
    volumes:
     - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sato
      MYSQL_PASSWORD: sato
      LANG: ja_JP.UTF-8
